version: "2"
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    gosec:
      excludes:
      - G115
    dupl:
      threshold: 100
    funlen:
      lines: 130
      statements: 60
    goconst:
      min-len: 5
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - gosec
          - maligned
        path: _test\.go
      - linters:
          - funlen
          - goconst
          - gocyclo
        path: cmd/chgogen
      - linters:
          - funlen
          - goconst
          - gocyclo
          - lll
        path: cmd/chtuplegen
      - linters:
          - dupl
        path: _unsafe\.go
      - linters:
          - dupl
          - goconst
          - gocritic
        path: main\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
