package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

type columnsConfig struct {
	input    string
	withIter bool
}

func runColumns(args []string) error {
	var cfg columnsConfig
	fs := flag.NewFlagSet("columns", flag.ExitOnError)
	fs.StringVar(&cfg.input, "input", "", "Input Go file (default: $GOFILE)")
	fs.BoolVar(&cfg.withIter, "with-iter", false, "Generate Iter() method")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if cfg.input == "" {
		cfg.input = os.Getenv("GOFILE")
	}
	if cfg.input == "" {
		return errors.New("--input is required (or run via go:generate)")
	}

	base := strings.TrimSuffix(cfg.input, filepath.Ext(cfg.input))
	outFile := base + "_columns_gen.go"

	return generateColumns(cfg.input, outFile, cfg.withIter)
}

// fieldInfo describes a single struct field with db/chtype tags.
type fieldInfo struct {
	Name   string
	GoType string
	DBName string
	ChType string
	Col    colInfo
}

// structInfo describes a struct with tagged fields.
type structInfo struct {
	Name   string
	Fields []fieldInfo
}

// typeString converts an AST type expression to a Go type string.
func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		// Fixed-size array like [16]byte
		if lit, ok := t.Len.(*ast.BasicLit); ok && lit.Kind == token.INT {
			return "[" + lit.Value + "]" + typeString(t.Elt)
		}
		return "[]" + typeString(t.Elt)
	case *ast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// generateColumns parses inputFile, finds tagged structs, and writes generated code to outFile.
func generateColumns(inputFile, outFile string, withIter bool) error {
	absInput, err := filepath.Abs(inputFile)
	if err != nil {
		return fmt.Errorf("resolving input path: %w", err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedTypes,
		Fset: token.NewFileSet(),
		Dir:  filepath.Dir(absInput),
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return fmt.Errorf("loading package: %w", err)
	}
	if len(pkgs) == 0 {
		return errors.New("no packages found")
	}

	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return fmt.Errorf("package errors: %v", pkg.Errors)
	}

	// Find the syntax file matching absInput
	var targetFile *ast.File
	for _, f := range pkg.Syntax {
		pos := cfg.Fset.Position(f.Pos())
		if filepath.Clean(pos.Filename) == filepath.Clean(absInput) {
			targetFile = f
			break
		}
	}
	if targetFile == nil {
		return fmt.Errorf("could not find syntax file for %s", absInput)
	}

	pkgName := pkg.Name

	// Walk AST to find structs with tagged fields
	var structs []structInfo
	ast.Inspect(targetFile, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		si := structInfo{Name: typeSpec.Name.Name}
		for _, field := range structType.Fields.List {
			if field.Tag == nil {
				continue
			}
			rawTag := strings.Trim(field.Tag.Value, "`")
			tag := reflect.StructTag(rawTag)

			dbName := tag.Get("db")
			if dbName == "" || dbName == "-" {
				continue
			}
			chType := tag.Get("chtype")
			if chType == "" {
				continue
			}

			if len(field.Names) == 0 {
				continue
			}
			fieldName := field.Names[0].Name
			goType := typeString(field.Type)

			ci, err := colMapping(goType, chType)
			if err != nil {
				// Skip fields we can't map (log to stderr)
				fmt.Fprintf(os.Stderr, "warning: skipping field %s.%s: %v\n", typeSpec.Name.Name, fieldName, err)
				continue
			}

			si.Fields = append(si.Fields, fieldInfo{
				Name:   fieldName,
				GoType: goType,
				DBName: dbName,
				ChType: chType,
				Col:    ci,
			})
		}

		if len(si.Fields) > 0 {
			structs = append(structs, si)
		}
		return true
	})

	if len(structs) == 0 {
		return errors.New("no structs with db+chtype tags found")
	}

	// Generate output code
	var buf bytes.Buffer
	buf.WriteString("// Code generated by chgen columns; DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	for _, s := range structs {
		writeColumnsStruct(&buf, s, withIter)
	}

	// Run goimports on the output
	formatted, err := imports.Process(outFile, buf.Bytes(), nil)
	if err != nil {
		// Fall back to unformatted if goimports fails
		formatted = buf.Bytes()
	}

	if err := os.WriteFile(outFile, formatted, 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}
	return nil
}

func writeColumnsStruct(buf *bytes.Buffer, s structInfo, withIter bool) {
	name := s.Name
	colsName := name + "Columns"

	// Struct definition
	fmt.Fprintf(buf, "// %s holds the columns for reading/writing %s rows.\n", colsName, name)
	fmt.Fprintf(buf, "type %s struct {\n", colsName)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\t%s %s\n", f.Name, f.Col.fieldType)
	}
	fmt.Fprintf(buf, "}\n\n")

	// Constructor
	fmt.Fprintf(buf, "// New%s creates a new %s with all columns initialized.\n", colsName, colsName)
	fmt.Fprintf(buf, "func New%s() *%s {\n", colsName, colsName)
	fmt.Fprintf(buf, "\tt := &%s{\n", colsName)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\t\t%s: %s,\n", f.Name, f.Col.constructor)
	}
	fmt.Fprintf(buf, "\t}\n")
	// SetName calls
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\tt.%s.SetName([]byte(%q))\n", f.Name, f.DBName)
	}
	// SetStrict(false) calls
	for _, f := range s.Fields {
		if f.Col.needsStrictFalse {
			fmt.Fprintf(buf, "\tt.%s.SetStrict(false)\n", f.Name)
		}
	}
	fmt.Fprintf(buf, "\treturn t\n")
	fmt.Fprintf(buf, "}\n\n")

	// Columns() method
	fmt.Fprintf(buf, "// Columns returns the list of ColumnCore for use with SelectStmt.\n")
	fmt.Fprintf(buf, "func (t *%s) Columns() []column.ColumnCore {\n", colsName)
	fmt.Fprintf(buf, "\treturn []column.ColumnCore{\n")
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\t\tt.%s,\n", f.Name)
	}
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	// Write() method
	fmt.Fprintf(buf, "// Write appends a single %s row to all columns.\n", name)
	fmt.Fprintf(buf, "func (t *%s) Write(m *%s) {\n", colsName, name)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\tt.%s.%s(m.%s)\n", f.Name, f.Col.appendMethod, f.Name)
	}
	fmt.Fprintf(buf, "}\n\n")

	// Read() method
	fmt.Fprintf(buf, "// Read reads a single row at index row from all columns.\n")
	fmt.Fprintf(buf, "func (t *%s) Read(row int) %s {\n", colsName, name)
	fmt.Fprintf(buf, "\treturn %s{\n", name)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\t\t%s: t.%s.%s(row),\n", f.Name, f.Name, f.Col.rowMethod)
	}
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	// SetWriteBufferSize() method
	fmt.Fprintf(buf, "// SetWriteBufferSize sets the write buffer size on all columns.\n")
	fmt.Fprintf(buf, "func (t *%s) SetWriteBufferSize(n int) {\n", colsName)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\tt.%s.SetWriteBufferSize(n)\n", f.Name)
	}
	fmt.Fprintf(buf, "}\n\n")

	// Reset() method
	fmt.Fprintf(buf, "// Reset resets all columns to empty.\n")
	fmt.Fprintf(buf, "func (t *%s) Reset() {\n", colsName)
	for _, f := range s.Fields {
		fmt.Fprintf(buf, "\tt.%s.Reset()\n", f.Name)
	}
	fmt.Fprintf(buf, "}\n\n")

	// Iter() method (optional)
	if withIter {
		fmt.Fprintf(buf, "// Iter returns an iterator over %s rows from a SelectStmt.\n", name)
		fmt.Fprintf(buf, "func (t *%s) Iter(stmt chconn.SelectStmt) iter.Seq2[%s, error] {\n", colsName, name)
		fmt.Fprintf(buf, "\treturn func(yield func(%s, error) bool) {\n", name)
		fmt.Fprintf(buf, "\t\tdefer stmt.Close()\n")
		fmt.Fprintf(buf, "\t\tfor n, err := range stmt.Iter() {\n")
		fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\t\t\tyield(%s{}, err)\n", name)
		fmt.Fprintf(buf, "\t\t\t\treturn\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
		fmt.Fprintf(buf, "\t\t\tfor i := range n {\n")
		fmt.Fprintf(buf, "\t\t\t\tif !yield(t.Read(i), nil) {\n")
		fmt.Fprintf(buf, "\t\t\t\t\treturn\n")
		fmt.Fprintf(buf, "\t\t\t\t}\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
		fmt.Fprintf(buf, "\t\t}\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "}\n\n")
	}
}
