package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestColumnsGenerate(t *testing.T) {
	tmpDir := t.TempDir()
	outFile := filepath.Join(tmpDir, "simple_model_columns_gen.go")

	err := generateColumns("testdata/simple_model.go", outFile, false)
	require.NoError(t, err)

	got, err := os.ReadFile(outFile)
	require.NoError(t, err)

	// Verify key parts of generated output
	content := string(got)
	require.Contains(t, content, "Code generated by chgen columns; DO NOT EDIT.")
	require.Contains(t, content, "type SimpleModelColumns struct {")
	require.Contains(t, content, "func NewSimpleModelColumns()")
	require.Contains(t, content, "func (t *SimpleModelColumns) Columns()")
	require.Contains(t, content, "func (t *SimpleModelColumns) Write(m *SimpleModel)")
	require.Contains(t, content, "func (t *SimpleModelColumns) Read(row int) SimpleModel")
	require.Contains(t, content, "func (t *SimpleModelColumns) SetWriteBufferSize(n int)")
	require.Contains(t, content, "func (t *SimpleModelColumns) Reset()")

	// Verify specific field mappings
	require.Contains(t, content, "*column.Base[uint64]")
	require.Contains(t, content, "*column.LowCardinality[string]")
	require.Contains(t, content, "*column.BaseNullable[int64]")
	require.Contains(t, content, "*column.Array[string]")
	require.Contains(t, content, "*column.Date[types.DateTime]")

	// Verify constructor calls
	require.Contains(t, content, "column.New[uint64]()")
	require.Contains(t, content, "column.NewString().LowCardinality()")
	require.Contains(t, content, "column.New[int64]().Nullable()")
	require.Contains(t, content, "column.NewString().LowCardinality().Array()")
	require.Contains(t, content, "column.NewDate[types.DateTime]()")

	// Verify SetName calls
	require.Contains(t, content, `SetName([]byte("id"))`)
	require.Contains(t, content, `SetName([]byte("name"))`)
	require.Contains(t, content, `SetName([]byte("created_at"))`)

	// Verify Write uses correct methods
	require.Contains(t, content, "t.ID.Append(m.ID)")
	require.Contains(t, content, "t.Score.AppendP(m.Score)")

	// Verify Read uses correct methods
	require.Contains(t, content, "t.ID.Row(row)")
	require.Contains(t, content, "t.Score.RowP(row)")

	// Verify IgnoreMe is NOT in the output
	require.NotContains(t, content, "IgnoreMe")
}

func TestColumnsGenerateWithIter(t *testing.T) {
	tmpDir := t.TempDir()
	outFile := filepath.Join(tmpDir, "simple_model_columns_gen.go")

	err := generateColumns("testdata/simple_model.go", outFile, true)
	require.NoError(t, err)

	got, err := os.ReadFile(outFile)
	require.NoError(t, err)

	content := string(got)
	require.Contains(t, content, "func (t *SimpleModelColumns) Iter(stmt chconn.SelectStmt) iter.Seq2[SimpleModel, error]")
	require.Contains(t, content, "t.Read(i)")
	require.Contains(t, content, "stmt.Close()")
}
