package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestToGoName(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"entity_id", "EntityId"},
		{"entityId", "EntityId"},
		{"ad_slotId", "AdSlotId"},
		{"id", "Id"},
		{"created_at", "CreatedAt"},
		{"some_field_name", "SomeFieldName"},
		{"myFieldName", "MyFieldName"},
		{"name", "Name"},
		{"source", "Source"},
		{"some.field.name", "SomeFieldName"},
		{"some-field-name", "SomeFieldName"},
		{"AdSlotId", "AdSlotId"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := toGoName(tt.input)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestExtractTableName(t *testing.T) {
	tests := []struct {
		name    string
		sql     string
		want    string
		wantErr bool
	}{
		{
			name: "simple create table",
			sql:  "CREATE TABLE events (id UInt64) ENGINE = MergeTree()",
			want: "events",
		},
		{
			name: "with IF NOT EXISTS",
			sql:  "CREATE TABLE IF NOT EXISTS events (id UInt64) ENGINE = MergeTree()",
			want: "events",
		},
		{
			name: "with database prefix",
			sql:  "CREATE TABLE mydb.events (id UInt64) ENGINE = MergeTree()",
			want: "events",
		},
		{
			name: "lowercase create table",
			sql:  "create table my_table (col1 String) ENGINE = Memory()",
			want: "my_table",
		},
		{
			name:    "no create table",
			sql:     "SELECT 1",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := extractTableName(tt.sql)
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestGenerateModel(t *testing.T) {
	columns := []columnSchema{
		{Name: "id", Type: "UInt64"},
		{Name: "name", Type: "LowCardinality(String)"},
		{Name: "score", Type: "Nullable(Int64)"},
		{Name: "source", Type: "Enum8('prebid' = 1, 'server' = 2)"},
		{Name: "created_at", Type: "DateTime"},
	}

	outFile := filepath.Join(t.TempDir(), "test_model.go")
	cfg := modelConfig{
		out:   outFile,
		pkg:   "testpkg",
		table: "events",
	}

	err := generateModel(cfg, columns)
	require.NoError(t, err)

	data, err := os.ReadFile(outFile)
	require.NoError(t, err)
	content := string(data)

	// Check code generated header
	require.Contains(t, content, "Code generated by chgen model; DO NOT EDIT.")

	// Check go:generate comment
	require.Contains(t, content, "//go:generate go tool chgen columns")

	// Check package declaration
	require.Contains(t, content, "package testpkg")

	// Check struct definition
	require.Contains(t, content, "type Events struct {")

	// Check field with db and chtype tags
	require.Contains(t, content, `db:"id"`)
	require.Contains(t, content, `chtype:"UInt64"`)

	require.Contains(t, content, `db:"name"`)
	require.Contains(t, content, `chtype:"LowCardinality(String)"`)

	require.Contains(t, content, `db:"score"`)
	require.Contains(t, content, `chtype:"Nullable(Int64)"`)

	require.Contains(t, content, `db:"source"`)
	require.Contains(t, content, `chtype:"Enum8('prebid' = 1, 'server' = 2)"`)

	require.Contains(t, content, `db:"created_at"`)
	require.Contains(t, content, `chtype:"DateTime"`)

	// Check enum type generated
	require.Contains(t, content, "type EventsSource")

	// Check enum constants
	require.Contains(t, content, "EventsSourcePrebid")
	require.Contains(t, content, "EventsSourceServer")

	// Check enum values use the type
	require.True(t, strings.Contains(content, "EventsSourcePrebid EventsSource = 1") ||
		strings.Contains(content, "EventsSourcePrebid\tEventsSource\t= 1"),
		"expected EventsSourcePrebid constant with value 1")

	// Check score field is nullable pointer
	require.True(t, strings.Contains(content, "*int64") || strings.Contains(content, "Score *int64"),
		"expected nullable field to have pointer type")

	// Check id field type
	require.True(t, strings.Contains(content, "uint64") || strings.Contains(content, "Id uint64"),
		"expected id field to have uint64 type")
}
