// Code generated by chgen columns; DO NOT EDIT.

package chgentest

import (
	"github.com/vahid-sohrabloo/chconn/v3/column"
	"github.com/vahid-sohrabloo/chconn/v3/types"
)

// ConvModelColumns holds the columns for reading/writing ConvModel rows.
type ConvModelColumns struct {
	ID      *column.Base[uint64]
	Flag    *column.Base[int8]
	Code    *column.LowCardinality[string]
	UID     *column.String
	Created *column.Date[types.DateTime]
}

// NewConvModelColumns creates a new ConvModelColumns with all columns initialized.
func NewConvModelColumns() *ConvModelColumns {
	t := &ConvModelColumns{
		ID:      column.New[uint64](),
		Flag:    column.New[int8](),
		Code:    column.NewString().LowCardinality(),
		UID:     column.NewString(),
		Created: column.NewDate[types.DateTime](),
	}
	t.ID.SetName([]byte("id"))
	t.ID.SetType([]byte("UInt64"))
	t.Flag.SetName([]byte("flag"))
	t.Flag.SetType([]byte("Int8"))
	t.Code.SetName([]byte("code"))
	t.Code.SetType([]byte("LowCardinality(String)"))
	t.UID.SetName([]byte("uid"))
	t.UID.SetType([]byte("String"))
	t.Created.SetName([]byte("created"))
	t.Created.SetType([]byte("DateTime"))
	return t
}

// Columns returns the list of ColumnCore for use with SelectStmt.
func (t *ConvModelColumns) Columns() []column.ColumnCore {
	return []column.ColumnCore{
		t.ID,
		t.Flag,
		t.Code,
		t.UID,
		t.Created,
	}
}

// Write appends a single ConvModel row to all columns.
func (t *ConvModelColumns) Write(m *ConvModel) {
	t.ID.Append(m.ID)
	t.Flag.Append(int8(m.Flag))
	t.Code.Append(string(m.Code))
	t.UID.Append(m.UID.String())
	t.Created.Append(unixTime(m.Created))
}

// Read reads a single row at index row from all columns.
func (t *ConvModelColumns) Read(row int) ConvModel {
	return ConvModel{
		ID:   t.ID.Row(row),
		Flag: ConvFlag(t.Flag.Row(row)),
		Code: ConvCode(t.Code.Row(row)),
		// TODO: UID uses chconv, which Read cannot invert
		// TODO: Created uses chconv, which Read cannot invert
	}
}

// SetWriteBufferSize sets the write buffer size on all columns.
func (t *ConvModelColumns) SetWriteBufferSize(n int) {
	t.ID.SetWriteBufferSize(n)
	t.Flag.SetWriteBufferSize(n)
	t.Code.SetWriteBufferSize(n)
	t.UID.SetWriteBufferSize(n)
	t.Created.SetWriteBufferSize(n)
}

// Reset resets all columns to empty.
func (t *ConvModelColumns) Reset() {
	t.ID.Reset()
	t.Flag.Reset()
	t.Code.Reset()
	t.UID.Reset()
	t.Created.Reset()
}

// ColumnNames returns a comma-separated list of column names for use in SELECT queries.
func (t *ConvModelColumns) ColumnNames() string {
	return "id, flag, code, uid, created"
}

// InsertQuery returns the INSERT INTO query for the given table.
func (t *ConvModelColumns) InsertQuery(table string) string {
	return "INSERT INTO " + table + " (id, flag, code, uid, created) VALUES"
}

// NumRows returns the number of rows written.
func (t *ConvModelColumns) NumRows() int {
	return t.ID.NumRow()
}

// CastModelColumns holds the columns for reading/writing CastModel rows.
type CastModelColumns struct {
	Byte  *column.Base[uint8]
	Alias *column.Base[uint16]
	Opt   *column.Base[int8]
	Code  *column.LowCardinality[string]
}

// NewCastModelColumns creates a new CastModelColumns with all columns initialized.
func NewCastModelColumns() *CastModelColumns {
	t := &CastModelColumns{
		Byte:  column.New[uint8](),
		Alias: column.New[uint16](),
		Opt:   column.New[int8](),
		Code:  column.NewString().LowCardinality(),
	}
	t.Byte.SetName([]byte("byte"))
	t.Byte.SetType([]byte("UInt8"))
	t.Alias.SetName([]byte("alias"))
	t.Alias.SetType([]byte("UInt16"))
	t.Opt.SetName([]byte("opt"))
	t.Opt.SetType([]byte("Int8"))
	t.Code.SetName([]byte("code"))
	t.Code.SetType([]byte("LowCardinality(String)"))
	return t
}

// Columns returns the list of ColumnCore for use with SelectStmt.
func (t *CastModelColumns) Columns() []column.ColumnCore {
	return []column.ColumnCore{
		t.Byte,
		t.Alias,
		t.Opt,
		t.Code,
	}
}

// Write appends a single CastModel row to all columns.
func (t *CastModelColumns) Write(m *CastModel) {
	t.Byte.Append(m.Byte)
	t.Alias.Append(m.Alias)
	t.Opt.Append(int8(m.Opt))
	t.Code.Append(string(codeOf(m.Code)))
}

// Read reads a single row at index row from all columns.
func (t *CastModelColumns) Read(row int) CastModel {
	return CastModel{
		Byte:  t.Byte.Row(row),
		Alias: t.Alias.Row(row),
		Opt:   ConvOpt[int](t.Opt.Row(row)),
		// TODO: Code uses chconv, which Read cannot invert
	}
}

// SetWriteBufferSize sets the write buffer size on all columns.
func (t *CastModelColumns) SetWriteBufferSize(n int) {
	t.Byte.SetWriteBufferSize(n)
	t.Alias.SetWriteBufferSize(n)
	t.Opt.SetWriteBufferSize(n)
	t.Code.SetWriteBufferSize(n)
}

// Reset resets all columns to empty.
func (t *CastModelColumns) Reset() {
	t.Byte.Reset()
	t.Alias.Reset()
	t.Opt.Reset()
	t.Code.Reset()
}

// ColumnNames returns a comma-separated list of column names for use in SELECT queries.
func (t *CastModelColumns) ColumnNames() string {
	return "byte, alias, opt, code"
}

// InsertQuery returns the INSERT INTO query for the given table.
func (t *CastModelColumns) InsertQuery(table string) string {
	return "INSERT INTO " + table + " (byte, alias, opt, code) VALUES"
}

// NumRows returns the number of rows written.
func (t *CastModelColumns) NumRows() int {
	return t.Byte.NumRow()
}
