// Code generated by chgen columns; DO NOT EDIT.

package chgentest

import (
	"github.com/vahid-sohrabloo/chconn/v3/column"
	"github.com/vahid-sohrabloo/chconn/v3/types"
)

// TestModelColumns holds the columns for reading/writing TestModel rows.
type TestModelColumns struct {
	ID             *column.Base[uint64]
	Name           *column.String
	Score          *column.Base[float64]
	Active         *column.Base[bool]
	SmallNum       *column.Base[int8]
	Category       *column.LowCardinality[string]
	NullScore      *column.BaseNullable[int64]
	NullName       *column.StringNullable[string]
	CreatedAt      *column.Date[types.DateTime]
	UpdatedAt      *column.Base[uint32]
	CountryCode    *column.Base[[2]byte]
	LangCode       *column.LowCardinality[[2]byte]
	Tags           *column.Array[string]
	Metadata       *column.Map[string, string]
	Status         *column.Base[TestModelStatus]
	UUID           *column.Base[types.UUID]
	Location       *column.Tuple2[types.Point, float64, float64]
	DeletedAt      *column.DateNullable[types.DateTime]
	OptionalScores *column.ArrayNullable[int64]
	TagGroups      *column.Array2[string]
	NullCategory   *column.LowCardinalityNullable[string]
	OptionalMeta   *column.MapNullable[string, int64]
}

// NewTestModelColumns creates a new TestModelColumns with all columns initialized.
func NewTestModelColumns() *TestModelColumns {
	t := &TestModelColumns{
		ID:             column.New[uint64](),
		Name:           column.NewString(),
		Score:          column.New[float64](),
		Active:         column.New[bool](),
		SmallNum:       column.New[int8](),
		Category:       column.NewString().LowCardinality(),
		NullScore:      column.New[int64]().Nullable(),
		NullName:       column.NewString().Nullable(),
		CreatedAt:      column.NewDate[types.DateTime](),
		UpdatedAt:      column.New[uint32](),
		CountryCode:    column.New[[2]byte](),
		LangCode:       column.New[[2]byte]().LowCardinality(),
		Tags:           column.NewString().Array(),
		Metadata:       column.NewMap[string, string](column.NewString(), column.NewString()),
		Status:         column.New[TestModelStatus](),
		UUID:           column.New[types.UUID](),
		Location:       column.NewPoint(),
		DeletedAt:      column.NewDate[types.DateTime]().Nullable(),
		OptionalScores: column.New[int64]().Nullable().Array(),
		TagGroups:      column.NewString().Array().Array(),
		NullCategory:   column.NewString().LowCardinality().Nullable(),
		OptionalMeta:   column.NewMapNullable[string, int64](column.NewString(), column.New[int64]().Nullable()),
	}
	t.ID.SetName([]byte("id"))
	t.Name.SetName([]byte("name"))
	t.Score.SetName([]byte("score"))
	t.Active.SetName([]byte("active"))
	t.SmallNum.SetName([]byte("small_num"))
	t.Category.SetName([]byte("category"))
	t.NullScore.SetName([]byte("null_score"))
	t.NullName.SetName([]byte("null_name"))
	t.CreatedAt.SetName([]byte("created_at"))
	t.UpdatedAt.SetName([]byte("updated_at"))
	t.CountryCode.SetName([]byte("country_code"))
	t.LangCode.SetName([]byte("lang_code"))
	t.Tags.SetName([]byte("tags"))
	t.Metadata.SetName([]byte("metadata"))
	t.Status.SetName([]byte("status"))
	t.UUID.SetName([]byte("uuid"))
	t.Location.SetName([]byte("location"))
	t.DeletedAt.SetName([]byte("deleted_at"))
	t.OptionalScores.SetName([]byte("optional_scores"))
	t.TagGroups.SetName([]byte("tag_groups"))
	t.NullCategory.SetName([]byte("null_category"))
	t.OptionalMeta.SetName([]byte("optional_meta"))
	t.UpdatedAt.SetStrict(false)
	return t
}

// Columns returns the list of ColumnCore for use with SelectStmt.
func (t *TestModelColumns) Columns() []column.ColumnCore {
	return []column.ColumnCore{
		t.ID,
		t.Name,
		t.Score,
		t.Active,
		t.SmallNum,
		t.Category,
		t.NullScore,
		t.NullName,
		t.CreatedAt,
		t.UpdatedAt,
		t.CountryCode,
		t.LangCode,
		t.Tags,
		t.Metadata,
		t.Status,
		t.UUID,
		t.Location,
		t.DeletedAt,
		t.OptionalScores,
		t.TagGroups,
		t.NullCategory,
		t.OptionalMeta,
	}
}

// Write appends a single TestModel row to all columns.
func (t *TestModelColumns) Write(m *TestModel) {
	t.ID.Append(m.ID)
	t.Name.Append(m.Name)
	t.Score.Append(m.Score)
	t.Active.Append(m.Active)
	t.SmallNum.Append(m.SmallNum)
	t.Category.Append(m.Category)
	t.NullScore.AppendP(m.NullScore)
	t.NullName.AppendP(m.NullName)
	t.CreatedAt.Append(m.CreatedAt)
	t.UpdatedAt.Append(m.UpdatedAt)
	t.CountryCode.Append(m.CountryCode)
	t.LangCode.Append(m.LangCode)
	t.Tags.Append(m.Tags)
	t.Metadata.Append(m.Metadata)
	t.Status.Append(m.Status)
	t.UUID.Append(m.UUID)
	t.Location.Append(m.Location)
	t.DeletedAt.AppendP(m.DeletedAt)
	t.OptionalScores.AppendP(m.OptionalScores)
	t.TagGroups.Append(m.TagGroups)
	t.NullCategory.AppendP(m.NullCategory)
	t.OptionalMeta.AppendP(m.OptionalMeta)
}

// Read reads a single row at index row from all columns.
func (t *TestModelColumns) Read(row int) TestModel {
	return TestModel{
		ID:             t.ID.Row(row),
		Name:           t.Name.Row(row),
		Score:          t.Score.Row(row),
		Active:         t.Active.Row(row),
		SmallNum:       t.SmallNum.Row(row),
		Category:       t.Category.Row(row),
		NullScore:      t.NullScore.RowP(row),
		NullName:       t.NullName.RowP(row),
		CreatedAt:      t.CreatedAt.Row(row),
		UpdatedAt:      t.UpdatedAt.Row(row),
		CountryCode:    t.CountryCode.Row(row),
		LangCode:       t.LangCode.Row(row),
		Tags:           t.Tags.Row(row),
		Metadata:       t.Metadata.Row(row),
		Status:         t.Status.Row(row),
		UUID:           t.UUID.Row(row),
		Location:       t.Location.Row(row),
		DeletedAt:      t.DeletedAt.RowP(row),
		OptionalScores: t.OptionalScores.RowP(row),
		TagGroups:      t.TagGroups.Row(row),
		NullCategory:   t.NullCategory.RowP(row),
		OptionalMeta:   t.OptionalMeta.RowP(row),
	}
}

// SetWriteBufferSize sets the write buffer size on all columns.
func (t *TestModelColumns) SetWriteBufferSize(n int) {
	t.ID.SetWriteBufferSize(n)
	t.Name.SetWriteBufferSize(n)
	t.Score.SetWriteBufferSize(n)
	t.Active.SetWriteBufferSize(n)
	t.SmallNum.SetWriteBufferSize(n)
	t.Category.SetWriteBufferSize(n)
	t.NullScore.SetWriteBufferSize(n)
	t.NullName.SetWriteBufferSize(n)
	t.CreatedAt.SetWriteBufferSize(n)
	t.UpdatedAt.SetWriteBufferSize(n)
	t.CountryCode.SetWriteBufferSize(n)
	t.LangCode.SetWriteBufferSize(n)
	t.Tags.SetWriteBufferSize(n)
	t.Metadata.SetWriteBufferSize(n)
	t.Status.SetWriteBufferSize(n)
	t.UUID.SetWriteBufferSize(n)
	t.Location.SetWriteBufferSize(n)
	t.DeletedAt.SetWriteBufferSize(n)
	t.OptionalScores.SetWriteBufferSize(n)
	t.TagGroups.SetWriteBufferSize(n)
	t.NullCategory.SetWriteBufferSize(n)
	t.OptionalMeta.SetWriteBufferSize(n)
}

// Reset resets all columns to empty.
func (t *TestModelColumns) Reset() {
	t.ID.Reset()
	t.Name.Reset()
	t.Score.Reset()
	t.Active.Reset()
	t.SmallNum.Reset()
	t.Category.Reset()
	t.NullScore.Reset()
	t.NullName.Reset()
	t.CreatedAt.Reset()
	t.UpdatedAt.Reset()
	t.CountryCode.Reset()
	t.LangCode.Reset()
	t.Tags.Reset()
	t.Metadata.Reset()
	t.Status.Reset()
	t.UUID.Reset()
	t.Location.Reset()
	t.DeletedAt.Reset()
	t.OptionalScores.Reset()
	t.TagGroups.Reset()
	t.NullCategory.Reset()
	t.OptionalMeta.Reset()
}

// ColumnNames returns a comma-separated list of column names for use in SELECT queries.
func (t *TestModelColumns) ColumnNames() string {
	return "id, name, score, active, small_num, category, null_score, null_name, created_at, updated_at, country_code, lang_code, tags, metadata, status, uuid, location, deleted_at, optional_scores, tag_groups, null_category, optional_meta"
}

// InsertQuery returns the INSERT INTO query for the given table.
func (t *TestModelColumns) InsertQuery(table string) string {
	return "INSERT INTO " + table + " (id, name, score, active, small_num, category, null_score, null_name, created_at, updated_at, country_code, lang_code, tags, metadata, status, uuid, location, deleted_at, optional_scores, tag_groups, null_category, optional_meta) VALUES"
}
