// Code generated by chgen columns; DO NOT EDIT.

package chgentest

import (
	"github.com/vahid-sohrabloo/chconn/v3/column"
	"github.com/vahid-sohrabloo/chconn/v3/types"
)

// TestModelColumns holds the columns for reading/writing TestModel rows.
type TestModelColumns struct {
	ID          *column.Base[uint64]
	Name        *column.String
	Score       *column.Base[float64]
	Active      *column.Base[bool]
	SmallNum    *column.Base[int8]
	Category    *column.LowCardinality[string]
	NullScore   *column.BaseNullable[int64]
	NullName    *column.StringNullable[string]
	CreatedAt   *column.Date[types.DateTime]
	UpdatedAt   *column.Base[uint32]
	CountryCode *column.Base[[2]byte]
	LangCode    *column.LowCardinality[[2]byte]
	Tags        *column.Array[string]
	Metadata    *column.Map[string, string]
	Status      *column.Base[TestModelStatus]
	UUID        *column.Base[types.UUID]
}

// NewTestModelColumns creates a new TestModelColumns with all columns initialized.
func NewTestModelColumns() *TestModelColumns {
	t := &TestModelColumns{
		ID:          column.New[uint64](),
		Name:        column.NewString(),
		Score:       column.New[float64](),
		Active:      column.New[bool](),
		SmallNum:    column.New[int8](),
		Category:    column.NewString().LowCardinality(),
		NullScore:   column.New[int64]().Nullable(),
		NullName:    column.NewString().Nullable(),
		CreatedAt:   column.NewDate[types.DateTime](),
		UpdatedAt:   column.New[uint32](),
		CountryCode: column.New[[2]byte](),
		LangCode:    column.New[[2]byte]().LowCardinality(),
		Tags:        column.NewString().Array(),
		Metadata:    column.NewMap[string, string](column.NewString(), column.NewString()),
		Status:      column.New[TestModelStatus](),
		UUID:        column.New[types.UUID](),
	}
	t.ID.SetName([]byte("id"))
	t.Name.SetName([]byte("name"))
	t.Score.SetName([]byte("score"))
	t.Active.SetName([]byte("active"))
	t.SmallNum.SetName([]byte("small_num"))
	t.Category.SetName([]byte("category"))
	t.NullScore.SetName([]byte("null_score"))
	t.NullName.SetName([]byte("null_name"))
	t.CreatedAt.SetName([]byte("created_at"))
	t.UpdatedAt.SetName([]byte("updated_at"))
	t.CountryCode.SetName([]byte("country_code"))
	t.LangCode.SetName([]byte("lang_code"))
	t.Tags.SetName([]byte("tags"))
	t.Metadata.SetName([]byte("metadata"))
	t.Status.SetName([]byte("status"))
	t.UUID.SetName([]byte("uuid"))
	t.UpdatedAt.SetStrict(false)
	return t
}

// Columns returns the list of ColumnCore for use with SelectStmt.
func (t *TestModelColumns) Columns() []column.ColumnCore {
	return []column.ColumnCore{
		t.ID,
		t.Name,
		t.Score,
		t.Active,
		t.SmallNum,
		t.Category,
		t.NullScore,
		t.NullName,
		t.CreatedAt,
		t.UpdatedAt,
		t.CountryCode,
		t.LangCode,
		t.Tags,
		t.Metadata,
		t.Status,
		t.UUID,
	}
}

// Write appends a single TestModel row to all columns.
func (t *TestModelColumns) Write(m *TestModel) {
	t.ID.Append(m.ID)
	t.Name.Append(m.Name)
	t.Score.Append(m.Score)
	t.Active.Append(m.Active)
	t.SmallNum.Append(m.SmallNum)
	t.Category.Append(m.Category)
	t.NullScore.AppendP(m.NullScore)
	t.NullName.AppendP(m.NullName)
	t.CreatedAt.Append(m.CreatedAt)
	t.UpdatedAt.Append(m.UpdatedAt)
	t.CountryCode.Append(m.CountryCode)
	t.LangCode.Append(m.LangCode)
	t.Tags.Append(m.Tags)
	t.Metadata.Append(m.Metadata)
	t.Status.Append(m.Status)
	t.UUID.Append(m.UUID)
}

// Read reads a single row at index row from all columns.
func (t *TestModelColumns) Read(row int) TestModel {
	return TestModel{
		ID:          t.ID.Row(row),
		Name:        t.Name.Row(row),
		Score:       t.Score.Row(row),
		Active:      t.Active.Row(row),
		SmallNum:    t.SmallNum.Row(row),
		Category:    t.Category.Row(row),
		NullScore:   t.NullScore.RowP(row),
		NullName:    t.NullName.RowP(row),
		CreatedAt:   t.CreatedAt.Row(row),
		UpdatedAt:   t.UpdatedAt.Row(row),
		CountryCode: t.CountryCode.Row(row),
		LangCode:    t.LangCode.Row(row),
		Tags:        t.Tags.Row(row),
		Metadata:    t.Metadata.Row(row),
		Status:      t.Status.Row(row),
		UUID:        t.UUID.Row(row),
	}
}

// SetWriteBufferSize sets the write buffer size on all columns.
func (t *TestModelColumns) SetWriteBufferSize(n int) {
	t.ID.SetWriteBufferSize(n)
	t.Name.SetWriteBufferSize(n)
	t.Score.SetWriteBufferSize(n)
	t.Active.SetWriteBufferSize(n)
	t.SmallNum.SetWriteBufferSize(n)
	t.Category.SetWriteBufferSize(n)
	t.NullScore.SetWriteBufferSize(n)
	t.NullName.SetWriteBufferSize(n)
	t.CreatedAt.SetWriteBufferSize(n)
	t.UpdatedAt.SetWriteBufferSize(n)
	t.CountryCode.SetWriteBufferSize(n)
	t.LangCode.SetWriteBufferSize(n)
	t.Tags.SetWriteBufferSize(n)
	t.Metadata.SetWriteBufferSize(n)
	t.Status.SetWriteBufferSize(n)
	t.UUID.SetWriteBufferSize(n)
}

// Reset resets all columns to empty.
func (t *TestModelColumns) Reset() {
	t.ID.Reset()
	t.Name.Reset()
	t.Score.Reset()
	t.Active.Reset()
	t.SmallNum.Reset()
	t.Category.Reset()
	t.NullScore.Reset()
	t.NullName.Reset()
	t.CreatedAt.Reset()
	t.UpdatedAt.Reset()
	t.CountryCode.Reset()
	t.LangCode.Reset()
	t.Tags.Reset()
	t.Metadata.Reset()
	t.Status.Reset()
	t.UUID.Reset()
}
